name: commit_checkout

on:
  push:
    branches:
      - main  # Replace 'main' with the branch you want to trigger this workflow on

jobs:
  external-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  # Updated to the latest version
        with:
          repository: abystoma/external-workflow
          ref: 3eb718710f20d7df6874acdc41e189a2ae4182f5

      - name: Greetings
        run: echo "$(<greeting.txt)"

